### PR TITLE
Fix handling of DOMAIN #10

### LINKED ISSUE #10: Problems with "domain" values in the objdictedit GUI tool
The objdictedit GUI tool seems to incorrectly manage "domain" values.

How to reproduce:
- launch the objdictedit GUI tool;
- File -> New;
- fill in the "Name:" field then click "OK";
- click the "0x2000-0x5FFF Manufacturer Specific" entry;
- click "Add" and add a map variable, Index 0x2000, "VAR" type, give it a name, and click "OK";
- click the new added variable, change the type to "DOMAIN";
- the following appears in the "value" field: `b''`;
- initialize the variable by changing the "value" field, then execute "Build Dictionary".

Here's the problem, because:
- if the value `b'00'`, or `b'11'`, or `b'25252525'` is entered, building the dictionary gives the error: "Domain variable not initialized, index: 0x2000, subindex: 0x00";
- if the value `12` is entered, when confirming the data the following error appears: <class 'AttributeError'>: 'bytes' object has no attribute 'encode';
- if the value `0x1234` is entered, when confirming the data the following error appears: <class 'binascii.Error'>: decoding with 'hex_codec' codec failed (Error: Non-hexadecimal digit found).

It seems there's no way to insert an acceptable value for "domain" fields.

Something similar happens when opening a `.od` file with the objdictedit GUI tool.
Here's an example.
Consider the 0x2300 entry, of "domain" type, with the hexadecimal value: `0x00000000000000`. It is 7 bytes long. The `.od` content is:
```
  <entry>
    <key type="numeric" value="8960" />
    <val type="string" value="\x00\x00\x00\x00\x00\x00\x00" />
  </entry>
```
When this `.od` file is opened by the objdictedit GUI tool, the value field shows: `b'5c7830305c7830305c7830305c7830305c7830305c7830305c783030'`, that's clearly not the expected one.
It should show `00000000000000`.
Now, without changing the value, executing "Build dictionary" succeeds. Anyway, the entry is generated like this, in the `.c` file:
```
UNS8 myDomainField[28] = "\x5c\x78\x30\x30\x5c\x78\x30\x30\x5c\x78\x30\x30\x5c\x78\x30\x30\x5c\x78\x30\x30\x5c\x78\x30\x30\x5c\x78\x30\x30";		/* Mapped at index 0x2300, subindex 0x00 */
```
Again, that's not the expected size and value. It should be:
```
UNS8 myDomainField[7] = "\x00\x00\x00\x00\x00\x00\x00";		/* Mapped at index 0x2300, subindex 0x00 */
```

Here's the behaviour of older versions of objdictedit (I mean: the ones working with Python 2 and wxPython 2.7).
The "domain" value accepted entries like `0x12fc` (it was transformed as `12fc` when confirmed), or like `12fc`.
The general rule was to accept any entry with an even quantity of hexadecimal characters. The entry could be prefixed by 0x, but it was not mandatory. If something different was entered, like non-hexadecimal characters or an odd quantity of characters, the entry was not accepted and the cell was filled back with the old valid value.

### PR DESCRIPTION
**Pull request by sveinse**
Fix #10 problems with DOMAIN.

* Fix UI editing of DOMAIN values
* Unicode DOMAIN doesn't work
* Add `odg cat` to odg as alias to `odg list`
* Print string length on `odg list` output
* Fixed encoding handling in nosis/XML
* Test suite update to reflect changes

### CODE REVIEW

**Comment by sarbazvatanatan** [comment]
[](url)

**Comment by sarbazvatanatan** [comment]
@sarbazvatanatan
